# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628ab32cb6570033232ea696b59f3fa9af5aa549852c14caaf5096974d1436a2b04922f60dfe8f933fa326da7ca787c2e4c2616733840f73a8995f9d3f31266b

test:
  secret_key_base: 372b334b88fbc35e690e2ae98d9aee708a9685e2c6027547b0d5e0da07d20a75dde499a0bfed86479fd0acabd92ed314db058d91bc58757a42885402d717bba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
